### ISSUE TITLE
Reddit wallpaper changer no longer opening

### ISSUE THREAD

**Issue by caxtell88** [Rawns/Reddit-Wallpaper-Changer#89]
I have no clue why it stopped opening all of a sudden on my home PC. When I try to run it no process is even starting for me, I look in Task Manager and nothing shows up. Not sure maybe a Windows update broke it I have Windows 10 Pro and did run an update a few nights ago but it happened a little after that.. Kind of an isolated incident I know. Maybe I'll just reinstall?

**Comment by caxtell88** [comment]
Well I did reinstall and did a little more digging looking at Event Viewer logs. I got two errors in the log which I will paste below

Application: Reddit Wallpaper Changer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at Reddit_Wallpaper_Changer.Properties.Settings.get_AppDataPath()
   at Reddit_Wallpaper_Changer.Database..ctor()
   at Reddit_Wallpaper_Changer.RWC..ctor()
   at Reddit_Wallpaper_Changer.Program.Main()
_______________________________________________________________________________________________________________

Faulting application name: Reddit Wallpaper Changer.exe, version: 1.0.13.0, time stamp: 0x58d9577b
Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0xade8d4fe
Exception code: 0xe0434352
Fault offset: 0x00111812
Faulting process id: 0x1da8
Faulting application start time: 0x01d4827ca76bb2a4
Faulting application path: C:\Program Files (x86)\Reddit Wallpaper Changer\Reddit Wallpaper Changer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6afd114a-e088-438c-9175-58b13c50157c
Faulting package full name: 
Faulting package-relative application ID: 

Doesn't look too promising and not sure how to fix, hopefully someone can figure this out because I love this app and want my daily wallpaper again :(

**Comment by 22justin** [comment]
im having this issue just starting now with the latest windows update.. any cure? uninstalled and reinstalled. app wont launch at all

**Comment by 22justin** [comment]
Application: Reddit Wallpaper Changer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at Reddit_Wallpaper_Changer.Properties.Settings.get_AppDataPath()
   at Reddit_Wallpaper_Changer.Database..ctor()
   at Reddit_Wallpaper_Changer.RWC..ctor()
   at Reddit_Wallpaper_Changer.Program.Main()

**Comment by 22justin** [comment]
Faulting application name: Reddit Wallpaper Changer.exe, version: 1.0.13.0, time stamp: 0x58d9577b
Faulting module name: KERNELBASE.dll, version: 10.0.17134.556, time stamp: 0xadca2670
Exception code: 0xe0434352
Fault offset: 0x001118a2
Faulting process id: 0x918
Faulting application start time: 0x01d4d243260f3d4b
Faulting application path: C:\Program Files (x86)\Reddit Wallpaper Changer\Reddit Wallpaper Changer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 93e1787e-46af-42e3-b9a2-fbced126c639
Faulting package full name: 
Faulting package-relative application ID:

**Comment by qwertydog** [comment]
Try my fork https://github.com/qwertydog/Reddit-Wallpaper-Changer/releases

There is a bug (https://github.com/Rawns/Reddit-Wallpaper-Changer/pull/79) in this version that occurs during startup. Same as this https://github.com/Rawns/Reddit-Wallpaper-Changer/issues/88
